import{a as L,S as B,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const u="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=";async function d(t,r){return(await L.get("https://pixabay.com/api/",{params:{key:"49187044-c2c4cc5e7c1f3c23966a70411",page:r,per_page:15,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const y=document.querySelector(".gallery"),f=document.querySelector(".gallery-button"),h=document.querySelector(".loader");let E=new B(".gallery a",{captions:!0,captionPosition:"bottom",captionDelay:250,captionsData:"alt"});function g(t){const r=t.map(({webformatURL:n,largeImageURL:c,tags:e,likes:o,views:i,comments:C,downloads:x})=>`<li class="gallery-item">
  <a href="${c}" class="gallery-link">
    <img src="${n}" alt="${e}" class="gallery-image" />
    <ul class="gallery-text">
      <li class="gallery-text-item">
        Likes<span class="gallery-span-item">${o}</span>
      </li>
      <li class="gallery-text-item">
        Views<span class="gallery-span-item">${i}</span>
      </li>
      <li class="gallery-text-item">
        Comments<span class="gallery-span-item">${C}</span>
      </li>
      <li class="gallery-text-item">Downloads<span class="gallery-span-item">${x}</span></li>
    </ul>
  </a>
</li>`).join("");y.insertAdjacentHTML("beforeend",r),E.refresh()}function P(){y.innerHTML=""}function A(){h.classList.remove("hidden")}function S(){h.classList.add("hidden")}function b(){f.classList.remove("hidden")}function m(){f.classList.add("hidden")}const R=document.querySelector(".form"),v=document.querySelector(".gallery"),z=document.querySelector(".gallery-button");let a=1,w=15,s="";R.addEventListener("submit",I);z.addEventListener("click",O);async function I(t){try{if(t.preventDefault(),P(),m(),s=t.target.elements["search-text"].value.toLowerCase().trim(),!s)return;A(),a=1;const r=await d(s,a);if(r.hits.length===0){l.error({iconUrl:u,title:"Error",class:"gallery-box",message:`Sorry, there are no images matching your search ${s}. Please try again!
`,position:"topRight",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",titleColor:"#fff"});return}a*w<r.totalHits?(g(r.hits),b()):(g(r.hits),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px"})),t.target.elements["search-text"].value=""}catch{l.error({iconUrl:u,title:"Error",class:"gallery-box",message:`Sorry, there are no images matching your search ${s}. Please try again!
`,position:"topRight",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",titleColor:"#fff",timeout:!1})}finally{S()}}function p(){const t=v.querySelector(".gallery-item"),{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}async function O(){try{a+=1,A(),m();const t=await d(s,a);if(a*w<t.totalHits)g(t.hits),p(),b();else return g(t.hits),p(),m(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px"})}catch{l.error({iconUrl:u,title:"Error",class:"gallery-box",message:`Sorry, there are no images matching your search ${s}. Please try again!
`,position:"topRight",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",titleColor:"#fff",timeout:!1})}finally{S()}}
//# sourceMappingURL=index.js.map
