import{a as C,S as x,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const p="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=";async function y(e,r){return(await C.get("https://pixabay.com/api/",{params:{key:"49187044-c2c4cc5e7c1f3c23966a70411",page:r,per_page:15,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const m=document.querySelector(".gallery"),u=document.querySelector(".hidden");let B=new x(".gallery a",{captions:!0,captionPosition:"bottom",captionDelay:250,captionsData:"alt"});function g(e){e.forEach(({webformatURL:r,largeImageURL:n,tags:c,likes:t,views:s,comments:i,downloads:w})=>m.insertAdjacentHTML("beforeend",`<li class="gallery-item">
  <a href="${n}" class="gallery-link">
    <img src="${r}" alt="${c}" class="gallery-image" />
    <ul class="gallery-text">
      <li class="gallery-text-item">
        Likes<span class="gallery-span-item">${t}</span>
      </li>
      <li class="gallery-text-item">
        Views<span class="gallery-span-item">${s}</span>
      </li>
      <li class="gallery-text-item">
        Comments<span class="gallery-span-item">${i}</span>
      </li>
      <li class="gallery-text-item">Downloads<span class="gallery-span-item">${w}</span></li>
    </ul>
  </a>
</li>`)),B.refresh()}function L(){m.innerHTML=""}function d(){u.insertAdjacentHTML("afterend",'<span class="loader"></span>')}function h(){const e=document.querySelector(".loader");e&&e.remove()}function A(){u.classList.add("gallery-button")}function S(){u.classList.remove("gallery-button")}function f(){const e=m.querySelector(".gallery-item"),{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}const E=document.querySelector(".form");let o=1,b=15,a="";E.addEventListener("submit",P);u.addEventListener("click",R);async function P(e){try{e.preventDefault(),L(),S(),a=e.currentTarget.elements["search-text"].value.toLowerCase().trim(),e.currentTarget.elements["search-text"].value="",o=1,d();const r=await y(a,o);if(r.hits.length===0){l.error({iconUrl:p,title:"Error",class:"gallery-box",message:`Sorry, there are no images matching your search ${a}. Please try again!
`,position:"topRight",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",titleColor:"#fff"});return}if(o*b<r.totalHits)o+=1,g(r.hits),A();else return g(r.hits),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px"})}catch{l.error({iconUrl:p,title:"Error",class:"gallery-box",message:`Sorry, there are no images matching your search ${a}. Please try again!
`,position:"topRight",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",titleColor:"#fff",timeout:!1})}finally{h()}}async function R(){try{d();const e=await y(a,o);if(o*b<e.totalHits)o+=1,g(e.hits),f(),A();else return g(e.hits),f(),S(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16px"})}catch{l.error({iconUrl:p,title:"Error",class:"gallery-box",message:`Sorry, there are no images matching your search ${a}. Please try again!
`,position:"topRight",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",titleColor:"#fff",timeout:!1})}finally{h()}}
//# sourceMappingURL=index.js.map
